### ISSUE TITLE
Check for existing sources when requested

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/issue-moderator-action#41]
### Expected behavior

- User creates a new source request issue in https://github.com/tachiyomiorg/tachiyomi-extensions/, including the URL
- Action checks if new issue is a source request
- If yes, then check repo `index.min.json` for duplicate URL.
  - If duplicate found, close issue and abort action
  - If no duplicate found, continue
- If no, continue

**Comment by alessandrojean** [comment]
Working on it.
